### ISSUE TITLE
[TODO] Aug.6th

### ISSUE THREAD

**Issue by ssm0318** [leegakyeong/OP#30]
앞으로 해야할 일들을 제가 생각나는 것만 추려봤어요!

- [ ] 1. 프로젝트 좋아요 기능 추가
- [ ] 2. routes 정리하기… 지금의 정리 방식이 약간 brute force라서 resources를 사용해서 잘 정리해보려고 합니다.
- [ ] 3. 파일 첨부 기능 (new를 form_for 사용해서 하기, placeholder 좀 더 적극적으로)
- [ ] 4. tag 기능 gem 써서 추가하도록 변경
- [ ] 5. style 완성 (show 페이지 꾸미기, 2~4 수정 이후 없어진 스타일링 보완)
- [ ] 6. 검색 기능 보완 (e.g. 전기를 검색하면 electricity가 나온다?)
- [ ] 7. 한국어화하기
- [ ] 8. 좋아요 기능 추가된 후 어떤 프로젝트들을 featured project에 올릴지 선별
- [ ] 9. deploy하기 (이건 개인적인 요청이지만 이 부분을 잘 몰라서 담당을 정하기보다는 같이 배워가면서 할 수 있으면 좋을 것 같아용!)
- [ ] +) 그 외… 어떻게 하면 지금 단계에서의 이 프로젝트를 완벽하게 할 수 있을까? 기획해보고 앞으로 보완할 점들을 팀원들에게 정리해주기! (e.g. user에게 별 주기, 이름 변경)

1은 @GooJinSun 가
2~4는 재원이가 ^_^
5~8, +) 는 @leegakyeong 가 해주면 좋을 것 같네용.

**Comment by ssm0318** [comment]
4번의 경우 tagging gem을 사용해보았지만 그리 깔끔하지 않은 것 같아서 기존의 방식을 유지하려고 합니다!
